[package]
name = "starks_proofgen"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]



[dependencies]
hex = "0.4.2"
rand = {version = "0.7.3",default-features = false}
blake3 = "0.3.5"
sha3 = "0.8.2"
crossbeam-utils = "0.8"
bincode = "1.3.1"
hashbrown = { version = "0.1.6", features = ["serde"] }
codec = { package = "parity-scale-codec", version = "2.0.0", features = [ "derive" ] }
serde_json = "1.0.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }
log = { version = "0.4.14", default-features = false }
sp-std = { version = "3.0.0", default-features = false }
sp-io = { version = "3.0.0", default-features = false }
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.74"
web-sys = "0.3.51"
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
wasm-bindgen-test = "0.3.24"
env_logger = "0.7.1"


[features]
default = ["std"]
std = [
	"sp-std/std",
	"sp-io/std",
	"codec/std",
    "rand/std",
]


[dev-dependencies]

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[profile.release]
debug = true